messages:
  prefix: "&b[룰렛]&r "
  created: "&a룰렛 &e%key%&a 가 생성되었습니다."
  exists: "&c이미 존재하는 키입니다: &e%key%"
  deleted: "&a룰렛 &e%key%&a 를 삭제했습니다."
  not_found: "&c해당 키의 룰렛이 없습니다: &e%key%"
  set_item_bind: "&a현재 손에 든 아이템을 &e%key%&a 룰렛 열쇠로 지정했습니다. (우클릭 시 뽑기)"
  need_item_in_hand: "&c손에 든 아이템이 없습니다."
  open_settings: "&a설정 GUI를 열었습니다: &e%key%"
  saved_settings: "&a설정이 저장되었습니다. 총 &e%count%개&a 아이템."
  open_preview: "&a확률/구성 미리보기: &e%key%"
  draw_start: "&a룰렛이 회전합니다!"
  draw_win: "&a축하합니다! &e%item%&a 를 획득했습니다!"
  no_items: "&c설정된 아이템이 없습니다. /랜덤 설정 %key% 로 등록하세요."
  setting_hint_1: "&7[Tip] 상단 인벤의 아이템을 &e좌클릭(+1) / 우클릭(-1)&7, &e쉬프트 클릭(±10)&7으로 가중치를 조절하세요."
  setting_hint_2: "&7[Tip] 인벤토리를 닫으면 현재 구성과 가중치가 저장됩니다."
  rare_broadcast: "&d&l[대박]&r &e%player%&r 님이 &b%key%&r 룰렛에서 &6가장 낮은 확률의 아이템&r &f[%item%]&r 을 뽑았습니다! 모두 축하해주세요!!"
  give_need_trigger: "&c해당 키의 열쇠 아이템이 설정되지 않았습니다. 먼저 /랜덤 아이템 %key% 로 지정하세요."
  give_player_not_found: "&c플레이어를 찾을 수 없습니다(온라인만)."
  give_invalid_amount: "&c올바른 수량을 입력하세요."
  give_success: "&a%player% 에게 &e%key%&a 열쇠 아이템을 &ex%amount%&a 지급했습니다."
titles:
  settings: "룰렛 설정: %key% (닫으면 저장)"
  preview: "룰렛 미리보기: %key%"
  spinner: "룰렛 뽑기: %key%"
gui:
  preview_draw_button_name: "&a[ 뽑기 시작 ]"
  preview_draw_button_lore:
    - "&7위 목록에서 확률을 확인하세요."
    - "&f클릭 시 27칸 룰렛이 회전합니다."
spinner:
  glass-name: "&f"
  ticks-per-step-start: 2
  extra-steps-random: 35
