# ============================================================
# UltimateRoulette - Config (v1.3.1 build-fix, updated)
# 주석을 참고해 서버 환경에 맞게 조정하세요.
# 기존 키는 그대로 유지되며, 새 옵션은 기본값으로 동작합니다.
# ============================================================

# 룰렛 회전 연출
spin:
  # 전체 회전 시간 (밀리초). 3000 = 3초
  total_ms: 3000
  # 회전 틱 간격 (작을수록 빠르게 슬롯이 바뀜). 1~4 권장
  tick_delay: 2

# GUI 제목 (색코드 & 사용 가능)
titles:
  spinner: "&6&l룰렛 스핀!"
  preview: "&d&l미리보기: %KEY%"
  edit: "&a&l설정: %KEY%"
  claim: "&b&l보관함 (클레임)"
  package: "&d&l패키지: %KEY%"
  package_edit: "&a&l패키지 설정: %KEY%"

# 자동 저장 주기 (틱). 20틱 = 1초, 600 = 30초
storage:
  save_interval_ticks: 600

# 우클릭/버튼 스팸 방지 쿨다운 (밀리초)
cooldown_ms: 700

# 사운드 커스터마이즈 (Spigot Sound enum 이름)
sounds:
  spin_tick: UI_BUTTON_CLICK
  spin_end: ENTITY_PLAYER_LEVELUP
  claim: ENTITY_ITEM_PICKUP

# 방송(브로드캐스트) 옵션 (false=끄기, true=켜기)
broadcasts:
  # 룰렛 당첨 시 방송 (미사용이면 무시)
  spin_win: false
  # 패키지 수령 시 방송 (미사용이면 무시)
  package_claim: false

# 고급 설정 (필요시만 건드리세요)
advanced:
  # 스핀 GUI 중복지급 방지 락 타임아웃 (ms). 네트워크 지연이 크면 약간 늘리세요.
  spin_lock_timeout_ms: 5000
  # 미리보기/보관함/설정 GUI에서의 최대 페이지 표시 제한(보안용)
  max_pages: 100


# 전용아이템 로어 템플릿 (색코드 & 사용 가능)
lore_templates:
  roulette:
    header:
      - "&7[전용 뽑기 아이템] &f%KEY%"
    line: "&7- &f%NAME%%COUNT% &7(&b%PERCENT%%&7)"
    footer:
      - "&8우클릭: 미리보기 / 스핀"
    # %KEY%: 키 이름
    # %NAME%: 보상 아이템명(첫 아이템 표시), %COUNT%: " x수량" 또는 빈 문자열
    # %PERCENT%: 소수점 2자리 확률
  package:
    header:
      - "&7[전용 패키지 아이템] &f%KEY%"
    line: "&7- &f%NAME%%COUNT%"
    footer:
      - "&8우클릭: 패키지 미리보기/수령"
    # %KEY%: 패키지 이름
    # %NAME%: 아이템명, %COUNT%: " x수량" 또는 빈 문자열
