name: UltimateRandomRoulette
main: com.minkang.ultimate.random.Main
version: 1.2.0
api-version: 1.16
author: MingangJeon+GPT
website: https://example.com/ultimate-random-roulette
commands:
  random:
    description: 랜덤 룰렛 관리 명령어 (/랜덤)
    aliases: [ "rr", "rnd", "랜덤" ]
    usage: "/랜덤 <생성|삭제|아이템|설정|목록|지급> (룰렛키)"
permissions:
  ultimate.random.admin:
    description: 랜덤 룰렛 관리자 권한
    default: op
