name: UltimateRoulette
main: com.minkang.ultimateroulette.UltimateRoulette
version: 1.7.2
api-version: 1.16
author: minkang
commands:
  roulette:
    description: Roulette system
    aliases: [랜덤, 룰렛]
    usage: /roulette
  package:
    description: Package system
    aliases: [패키지]
    usage: /package

permissions:
  ultimateroulette.admin:
    default: op
