name: UltimateRoulette
main: com.minkang.ultimateroulette.UltimateRoulette
version: 1.5.1
api-version: 1.16
author: minkang+gpt
commands:
  roulette:
    description: Roulette system
    aliases: [랜덤, 룰렛]
    usage: /roulette
permissions:
  ultimateroulette.admin:
    default: op

  package:
    description: Package system
    aliases: [패키지]
    usage: /package
