package com.minkang.ultimate.random.gui;
import com.minkang.ultimate.random.*; import org.bukkit.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*;
public class PreviewGUI implements Listener{
  private final Main plugin; public PreviewGUI(Main p){ this.plugin=p; }
  public static void open(Main plugin, Player p, Roulette r){ String title=plugin.getConfig().getString("titles.preview","룰렛 미리보기: %key%").replace("%key%", r.getKey());
    Inventory inv=Bukkit.createInventory(p,54, ChatColor.translateAlternateColorCodes('&', title)); int total=r.getTotalWeight(); java.text.DecimalFormat df=new java.text.DecimalFormat("#.##");
    int slot=0; for(RouletteEntry e:r.getEntries()){ if(slot>=45) break; org.bukkit.inventory.ItemStack it=e.getItem().clone(); org.bukkit.inventory.meta.ItemMeta m=it.getItemMeta();
      if(m!=null){ java.util.List<String> lore=m.hasLore()?m.getLore():new java.util.ArrayList<String>(); if(lore==null) lore=new java.util.ArrayList<String>(); double chance=100.0*e.getWeight()/Math.max(1,total); lore.add("§7확률: §e"+df.format(chance)+"% §7(가중치 "+e.getWeight()+")"); m.setLore(lore); it.setItemMeta(m);} inv.setItem(slot++, it); }
    ItemStack draw=new ItemStack(Material.EMERALD_BLOCK); org.bukkit.inventory.meta.ItemMeta dm=draw.getItemMeta(); if(dm!=null){ dm.setDisplayName(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("gui.preview_draw_button_name","&a[ 뽑기 시작 ]"))); java.util.List<String> lore=new java.util.ArrayList<String>(); for(String s: plugin.getConfig().getStringList("gui.preview_draw_button_lore")) lore.add(ChatColor.translateAlternateColorCodes('&', s)); dm.setLore(lore); draw.setItemMeta(dm);} inv.setItem(49, draw); p.openInventory(inv); p.sendMessage(plugin.msg("open_preview").replace("%key%", r.getKey())); }
  @EventHandler public void onClick(InventoryClickEvent e){ if(!(e.getWhoClicked() instanceof Player)) return; String title=e.getView().getTitle(); if(title==null) return; if(!ChatColor.stripColor(title).startsWith("룰렛 미리보기:")) return; e.setCancelled(true);
    if(e.getRawSlot()==49){ String plain=ChatColor.stripColor(title); String key=plain.replace("룰렛 미리보기:","").trim(); int idx=key.indexOf(" "); if(idx!=-1) key=key.substring(0,idx).trim(); Roulette r=plugin.getManager().get(key);
      if(r==null){ ((Player)e.getWhoClicked()).sendMessage(plugin.msg("not_found").replace("%key%", key)); e.getWhoClicked().closeInventory(); return; } if(r.isEmpty()){ ((Player)e.getWhoClicked()).sendMessage(plugin.msg("no_items")); e.getWhoClicked().closeInventory(); return; }
      e.getWhoClicked().closeInventory(); ((Player)e.getWhoClicked()).playSound(e.getWhoClicked().getLocation(), Sound.UI_BUTTON_CLICK, 1f, 1.2f); SpinnerGUI.start(plugin,(Player)e.getWhoClicked(), r); } }
}