package com.minkang.ultimate.random.gui;
import com.minkang.ultimate.random.*; import org.bukkit.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
import java.util.*; 
public class SettingsGUI implements Listener{
  private final Main plugin; public SettingsGUI(Main p){ this.plugin=p; }
  public static void open(Main plugin, Player p, Roulette r){ String title=plugin.getConfig().getString("titles.settings","룰렛 설정: %key% (닫으면 저장)").replace("%key%", r.getKey()); Inventory inv=Bukkit.createInventory(p,27, ChatColor.translateAlternateColorCodes('&', title));
    int i=0; for(RouletteEntry e:r.getEntries()){ if(i>=27) break; org.bukkit.inventory.ItemStack it=e.getItem().clone(); ItemMeta m=it.getItemMeta(); if(m!=null){ java.util.List<String> lore=m.hasLore()?m.getLore():new java.util.ArrayList<String>(); if(lore==null) lore=new java.util.ArrayList<String>(); lore.add("§7가중치: §e"+e.getWeight()); m.setLore(lore); it.setItemMeta(m);} inv.setItem(i++, it);} p.openInventory(inv); }
  @EventHandler public void onClose(InventoryCloseEvent e){ String t=e.getView().getTitle(); if(t==null) return; String plain=ChatColor.stripColor(t); if(!plain.startsWith("룰렛 설정:")) return; String key=plain.replace("룰렛 설정:","").trim(); int idx=key.indexOf(" "); if(idx!=-1) key=key.substring(0,idx).trim();
    Roulette r=plugin.getManager().get(key); if(r==null) return; java.util.List<RouletteEntry> list=new java.util.ArrayList<>(); for(int i=0;i<e.getInventory().getSize();i++){ org.bukkit.inventory.ItemStack it=e.getInventory().getItem(i); if(it==null||it.getType()==Material.AIR) continue; list.add(new RouletteEntry(it.clone(),1)); } r.setEntries(list); plugin.getManager().save(); if(e.getPlayer() instanceof Player){ ((Player)e.getPlayer()).sendMessage(plugin.msg("saved_settings").replace("%count%", String.valueOf(list.size())));} }
}