name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 + Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Fast Maven settings (central + papermc only)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <mirrors>
              <mirror>
                <id>central</id>
                <name>Maven Central</name>
                <url>https://repo1.maven.org/maven2/</url>
                <mirrorOf>central</mirrorOf>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>speed</id>
                <repositories>
                  <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2/</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                  <repository>
                    <id>papermc</id>
                    <url>https://repo.papermc.io/repository/maven-public/</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles><activeProfile>speed</activeProfile></activeProfiles>
          </settings>
          XML

      - name: Warm dependencies (go-offline)
        run: mvn -B -q -DskipTests dependency:go-offline

      - name: Build (fast)
        run: mvn -B -q -T 1C -DskipTests -Dmaven.javadoc.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true -Dgpg.skip=true package
